# Default values for airbyte-module.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/fybrik/airbyte-module
  tag: main
  pullPolicy: null
  pullSecret: null

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Additional connection properties that are passed to the Airbyte connector.
# If such exists, they are merged with the connection properties defined in Fybrik taxonomy to configure
# the Airbyte connector. Otherwise only the connection properties defined in Fybrik taxonomy are used.
# To process the properties according to connector type special metadata properties are defined:
# - expected_format: contains the format of the source/destination.
# - emit_format: if the key exists then the connection format should be emitted.
#
# The metadata properties are optional and are not passed to the connector.
connectors:
  mysql:
    # Specify properties for source.
    read:
      # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-mysql/src/main/resources/spec.json
      - replication_method:
          method: "STANDARD"
        connector: airbyte/source-mysql:0.6.13
    # Specify properties for destination.
    write:
      # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-mysql/src/main/resources/spec.json
      - connector: airbyte/destination-mysql:0.1.20
  google-sheets:
    # Specify properties for source.
    read:
      # https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-google-sheets/google_sheets_source/spec.yaml
      -  connector: airbyte/source-google-sheets:0.2.31
    # Specify properties for destination.
    write:
      # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-google-sheets/destination_google_sheets/spec.json
      - connector: airbyte/destination-google-sheets:0.1.2
  postgres:
    # Specify properties for source.
    read:
      # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-postgres/src/main/resources/spec.json
      - connector: airbyte/source-postgres:1.0.42
    write:
      # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-postgres/src/main/resources/spec.json
      - connector: airbyte/destination-postgres:0.3.26
        # The default schema tables are written to if the source does not specify a namespace. The usual value for this field is "public".
        schema: public
  us-census:
    # Specify properties for source.
    read:
      # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-us-census/source_us_census/spec.json
      - connector: airbyte/source-us-census:0.1.2
  localfile:
    write:
      - expected_format: json
        # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-local-json/src/main/resources/spec.json
        connector: airbyte/destination-local-json:0.2.11
      - expected_format: csv
        # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-local-json/src/main/resources/spec.json
        connector: airbyte/destination-csv:1.0.0
  https:
    # Specify properties for source.
    read:
      # ref: https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-file/source_file/spec.json
      - connector: airbyte/source-file:0.2.33
        emit_format: true
        provider:
          storage: HTTPS
        # dataset_name is the Name of the final table to replicate this file into.
        dataset_name: userdata

# Atttributes related to the normzliation process. If they are provided then
# normzliation process is applied.
# ref: https://docs.airbyte.com/understanding-airbyte/basic-normalization
normalization:
   mysql:
     image: airbyte/normalization-mysql:0.2.25
     integrationType: mysql
     airbyteVersion: 0.40.14
